import crypto from 'crypto';

/**
 * The customer's password for the myIQ Cognitive Training Program.
 *
 * Generated by us rather than chosen by the customer: the funnel never asks for
 * a password — it asks for a card — so the account has to arrive already usable,
 * with its credentials delivered in the welcome email.
 *
 * The plaintext is returned once, to be emailed, and never stored. Only the
 * bcrypt hash goes into `customers.password_hash`, so a database dump does not
 * hand over anyone's login, and support genuinely cannot read it back — a
 * forgotten password has to be reset, not recovered.
 */

/**
 * Deliberately excludes the characters people mistype when copying from an
 * email: 0/O, 1/I/L, and lowercase entirely. Someone reading this off a phone
 * and typing it into a laptop is the case to optimise for, not density.
 */
const ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

const GROUPS = 3;
const GROUP_SIZE = 4;

/**
 * A readable one-time password, e.g. `K7MP-3QRT-9XYZ`.
 *
 * Twelve characters from a 31-character alphabet is roughly 59 bits of entropy
 * — far beyond anything guessable, while still being something a person can
 * retype from a printed email without a mistake.
 *
 * Uses `randomInt`, not `Math.random`: this is a credential, and the modulo
 * bias of a naive `randomBytes` mapping would quietly shrink the keyspace.
 */
export function generateCustomerPassword(): string {
  const groups: string[] = [];

  for (let g = 0; g < GROUPS; g += 1) {
    let group = '';
    for (let i = 0; i < GROUP_SIZE; i += 1) {
      group += ALPHABET[crypto.randomInt(0, ALPHABET.length)];
    }
    groups.push(group);
  }

  return groups.join('-');
}
